# It uses your credentials defined for aws cli
# So you need installed aws cli on your machine with configured credentials to use serverless cli
service: service-template

frameworkVersion: '3'

plugins:
  - serverless-esbuild
  - serverless-latest-layer-version

package:
  individually: true
  excludeDevDependencies: true

custom:
  esbuild:
    minify: true
    bundle: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs16.x
  memorySize: 512
  timeout: 10 # 10 sec
  logRetentionInDays: 14
  architecture: arm64
  versionFunctions: false
  stage: dev
  environment:
    SERVICE_NAME: service-template

functions:

resources:
  Resources:
    db
    role
